sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  

matrix:
  include:
  
  - ghc: 8.4.4
    env: GHCVER='8.4.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-head
  

install:
  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - echo $PATH
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test

notifications:
  email: false
